version: '3.8'

services:
  postgres:
    container_name: postgis
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: smizc2024
      POSTGRES_USER: smizc
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432